spring:
  datasource:
    url: jdbc:mysql://localhost:3306/online_shop
    username: shop
    password: Coo2022*
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
#        dialect: org.hibernate.dialect.
        format_sql: true
server:
  port: 8080
  servlet:
    context-path: /product-service